# Pre-commit configuration

repos:
  # -----------------------------
  # Generic sanity checks
  # -----------------------------
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v6.0.0   # use a recent stable tag
    hooks:
      - id: trailing-whitespace        # remove trailing spaces
      - id: end-of-file-fixer          # ensure file ends with a newline
      - id: check-toml                 # validate TOML files (e.g. pyproject.toml)
      - id: check-yaml                 # validate YAML files (e.g. CI workflows)
      - id: check-json                 # validate JSON files
      - id: check-added-large-files    # prevent committing huge binaries accidentally

  # -----------------------------
  # Ruff (lint + format)
  # -----------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # -----------------------------
  # uv integration
  # -----------------------------
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.5
    hooks:
      - id: uv-lock


exclude: >
  ^(.svn|CVS|\.bzr|\.hg|\.git|__pycache__|\.tox|\.ipynb_checkpoints|assets|tests/assets/|venv/|\.venv/)
